package org.debs.mayday.core.designsystem.theme

import org.debs.mayday.core.model.AppLanguage

data class MaydayStrings(
    val appName: String,
    val tagline: String,
    val connect: String,
    val disconnect: String,
    val connecting: String,
    val connected: String,
    val disconnected: String,
    val reconnecting: String,
    val settings: String,
    val theme: String,
    val language: String,
    val density: String,
    val light: String,
    val dark: String,
    val compact: String,
    val comfortable: String,
    val profile: String,
    val splitRouting: String,
    val advanced: String,
    val diagnostics: String,
    val importConfig: String,
    val importFile: String,
    val manual: String,
    val continueLabel: String,
    val onboardingTitle: String,
    val onboardingSubtitle: String,
    val allTraffic: String,
    val onlySelected: String,
    val exceptSelected: String,
    val apps: String,
    val relay: String,
    val userId: String,
    val dns: String,
    val autoFailover: String,
    val current: String,
    val routingSummary: String,
    val saveProfile: String,
)

fun maydayStrings(language: AppLanguage): MaydayStrings {
    return when (language) {
        AppLanguage.RU -> MaydayStrings(
            appName = "mayday",
            tagline = "network client",
            connect = "РїРѕРґРєР»СЋС‡РёС‚СЊСЃСЏ",
            disconnect = "РѕС‚РєР»СЋС‡РёС‚СЊ",
            connecting = "РїРѕРґРєР»СЋС‡РµРЅРёРµ",
            connected = "РїРѕРґРєР»СЋС‡РµРЅРѕ",
            disconnected = "РѕС‚РєР»СЋС‡РµРЅРѕ",
            reconnecting = "РїРµСЂРµРїРѕРґРєР»СЋС‡РµРЅРёРµ",
            settings = "РЅР°СЃС‚СЂРѕР№РєРё",
            theme = "С‚РµРјР°",
            language = "СЏР·С‹Рє",
            density = "РїР»РѕС‚РЅРѕСЃС‚СЊ",
            light = "СЃРІРµС‚Р»Р°СЏ",
            dark = "С‚РµРјРЅР°СЏ",
            compact = "РєРѕРјРїР°РєС‚РЅР°СЏ",
            comfortable = "РѕР±С‹С‡РЅР°СЏ",
            profile = "РїСЂРѕС„РёР»СЊ",
            splitRouting = "split routing",
            advanced = "СЂР°СЃС€РёСЂРµРЅРЅС‹Рµ",
            diagnostics = "РґРёР°РіРЅРѕСЃС‚РёРєР°",
            importConfig = "РёРјРїРѕСЂС‚ РєРѕРЅС„РёРіСѓСЂР°С†РёРё",
            importFile = "С„Р°Р№Р»",
            manual = "РІСЂСѓС‡РЅСѓСЋ",
            continueLabel = "РїСЂРѕРїСѓСЃС‚РёС‚СЊ",
            onboardingTitle = "РїРѕРґРєР»СЋС‡РµРЅРёРµ",
            onboardingSubtitle = "РёРјРїРѕСЂС‚РёСЂСѓР№С‚Рµ РєРѕРЅС„РёРіСѓСЂР°С†РёСЋ РёР»Рё РѕС‚РєСЂРѕР№С‚Рµ РїСЂРѕС„РёР»СЊ РґР»СЏ СЂСѓС‡РЅРѕР№ РЅР°СЃС‚СЂРѕР№РєРё",
            allTraffic = "РІРµСЃСЊ С‚СЂР°С„РёРє",
            onlySelected = "С‚РѕР»СЊРєРѕ РІС‹Р±СЂР°РЅРЅС‹Рµ",
            exceptSelected = "РІСЃРµ РєСЂРѕРјРµ РІС‹Р±СЂР°РЅРЅС‹С…",
            apps = "РїСЂРёР»РѕР¶РµРЅРёСЏ",
            relay = "relay",
            userId = "user id",
            dns = "dns",
            autoFailover = "Р°РІС‚РѕРїРµСЂРµРєР»СЋС‡РµРЅРёРµ",
            current = "Р°РєС‚РёРІРЅС‹Р№",
            routingSummary = "СЂРµР¶РёРј РјР°СЂС€СЂСѓС‚РёР·Р°С†РёРё",
            saveProfile = "СЃРѕС…СЂР°РЅРёС‚СЊ РїСЂРѕС„РёР»СЊ",
        )
        AppLanguage.EN -> MaydayStrings(
            appName = "mayday",
            tagline = "network client",
            connect = "connect",
            disconnect = "disconnect",
            connecting = "connecting",
            connected = "connected",
            disconnected = "disconnected",
            reconnecting = "reconnecting",
            settings = "settings",
            theme = "theme",
            language = "language",
            density = "density",
            light = "light",
            dark = "dark",
            compact = "compact",
            comfortable = "comfortable",
            profile = "profile",
            splitRouting = "split routing",
            advanced = "advanced",
            diagnostics = "diagnostics",
            importConfig = "import config",
            importFile = "file",
            manual = "manual",
            continueLabel = "skip",
            onboardingTitle = "get connected",
            onboardingSubtitle = "import a config file or open the profile editor for manual setup",
            allTraffic = "all traffic",
            onlySelected = "only selected",
            exceptSelected = "all except selected",
            apps = "apps",
            relay = "relay",
            userId = "user id",
            dns = "dns",
            autoFailover = "auto failover",
            current = "active",
            routingSummary = "routing mode",
            saveProfile = "save profile",
        )
    }
}
