package org.debs.mayday.core.designsystem.theme

import org.debs.mayday.core.model.AppLanguage

data class MaydayStrings(
    val locale: AppLanguage,
    val appName: String,
    val tagline: String,
    val connect: String,
    val disconnect: String,
    val connecting: String,
    val connected: String,
    val disconnected: String,
    val reconnecting: String,
    val settings: String,
    val theme: String,
    val language: String,
    val density: String,
    val light: String,
    val dark: String,
    val compact: String,
    val comfortable: String,
    val profile: String,
    val splitRouting: String,
    val advanced: String,
    val diagnostics: String,
    val importConfig: String,
    val importFile: String,
    val manual: String,
    val continueLabel: String,
    val onboardingTitle: String,
    val onboardingSubtitle: String,
    val allTraffic: String,
    val onlySelected: String,
    val exceptSelected: String,
    val apps: String,
    val relay: String,
    val userId: String,
    val dns: String,
    val autoFailover: String,
    val current: String,
    val routingSummary: String,
    val saveProfile: String,
    val status: String,
    val detail: String,
    val engine: String,
    val ready: String,
    val missing: String,
    val servers: String,
    val priority: String,
    val notSet: String,
    val relayNotConfigured: String,
    val profileField: String,
    val port: String,
    val tun: String,
    val mtu: String,
    val keepSessionAliveHint: String,
    val importedFrom: String,
    val serversHint: String,
    val addServer: String,
    val remove: String,
    val server: String,
    val serverId: String,
    val serverKey: String,
    val loading: String,
    val saving: String,
    val preparingWorkspace: String,
    val showSystemApps: String,
    val showSystemAppsHint: String,
    val search: String,
    val noAppsFound: String,
    val noAppsFoundHint: String,
    val noPerAppSelectionHint: String,
    val onboardingImportHint: String,
    val onboardingManualHint: String,
    val onboardingContinueHint: String,
    val readSavedRoutingState: String,
    val readSplitRoutingState: String,
    val failedReadSelectedFile: String,
    val unableToOpenSelectedConfigFile: String,
    val failedImportSelectedFile: String,
    val failedImportConfig: String,
    val atLeastOneServerRequired: String,
    val atLeastOneAppRequired: String = "Select at least one app.",
    val profileSaved: String,
    val failedSaveProfile: String,
    val failedSaveRoutingSettings: String,
    val config: String,
)

fun maydayStrings(language: AppLanguage): MaydayStrings {
    return when (language) {
        AppLanguage.RU -> MaydayStrings(
            locale = AppLanguage.RU,
            appName = "mayday",
            tagline = "сетевой клиент",
            connect = "подключиться",
            disconnect = "отключиться",
            connecting = "подключение",
            connected = "подключено",
            disconnected = "отключено",
            reconnecting = "переподключение",
            settings = "настройки",
            theme = "тема",
            language = "язык",
            density = "плотность",
            light = "светлая",
            dark = "тёмная",
            compact = "компактная",
            comfortable = "обычная",
            profile = "профиль",
            splitRouting = "маршрутизация",
            advanced = "расширенные",
            diagnostics = "диагностика",
            importConfig = "импорт конфига",
            importFile = "файл",
            manual = "вручную",
            continueLabel = "пропустить",
            onboardingTitle = "подключение",
            onboardingSubtitle = "импортируйте конфигурацию или откройте профиль для ручной настройки",
            allTraffic = "весь трафик",
            onlySelected = "только выбранные",
            exceptSelected = "все кроме выбранных",
            apps = "приложения",
            relay = "relay",
            userId = "user id",
            dns = "dns",
            autoFailover = "автопереключение",
            current = "активный",
            routingSummary = "режим маршрутизации",
            saveProfile = "сохранить профиль",
            status = "статус",
            detail = "детали",
            engine = "движок",
            ready = "готов",
            missing = "недоступен",
            servers = "серверы",
            priority = "приоритет",
            notSet = "не задано",
            relayNotConfigured = "relay не настроен",
            profileField = "профиль",
            port = "порт",
            tun = "tun",
            mtu = "mtu",
            keepSessionAliveHint = "сохранять сессию при смене активного сетевого пути",
            importedFrom = "Импортировано из",
            serversHint = "vpncore получает весь массив servers[] и сам выбирает целевой сервер.",
            addServer = "добавить сервер",
            remove = "удалить",
            server = "сервер",
            serverId = "server id",
            serverKey = "server key",
            loading = "загрузка...",
            saving = "сохранение...",
            preparingWorkspace = "Подготавливаем рабочее пространство...",
            showSystemApps = "показывать системные приложения",
            showSystemAppsHint = "включить системные пакеты в список",
            search = "поиск",
            noAppsFound = "Приложения не найдены",
            noAppsFoundHint = "Измените поисковый запрос или включите системные приложения, чтобы увидеть больше пакетов.",
            noPerAppSelectionHint = "В этом режиме отдельный выбор приложений не требуется.",
            onboardingImportHint = "client.yaml / client.json",
            onboardingManualHint = "relay, user id, servers[]",
            onboardingContinueHint = "открыть главный экран без импорта",
            readSavedRoutingState = "Читаем сохранённый режим и список приложений...",
            readSplitRoutingState = "Читаем режим split routing и список приложений из хранилища.",
            failedReadSelectedFile = "Не удалось прочитать выбранный файл.",
            unableToOpenSelectedConfigFile = "Не удалось открыть выбранный конфиг.",
            failedImportSelectedFile = "Не удалось импортировать выбранный файл.",
            failedImportConfig = "Не удалось импортировать конфиг.",
            atLeastOneServerRequired = "Нужно указать хотя бы один сервер.",
            profileSaved = "Профиль сохранён",
            failedSaveProfile = "Не удалось сохранить профиль.",
            failedSaveRoutingSettings = "Не удалось сохранить настройки маршрутизации.",
            config = "конфиг",
        )
        AppLanguage.EN -> MaydayStrings(
            locale = AppLanguage.EN,
            appName = "mayday",
            tagline = "network client",
            connect = "connect",
            disconnect = "disconnect",
            connecting = "connecting",
            connected = "connected",
            disconnected = "disconnected",
            reconnecting = "reconnecting",
            settings = "settings",
            theme = "theme",
            language = "language",
            density = "density",
            light = "light",
            dark = "dark",
            compact = "compact",
            comfortable = "comfortable",
            profile = "profile",
            splitRouting = "split routing",
            advanced = "advanced",
            diagnostics = "diagnostics",
            importConfig = "import config",
            importFile = "file",
            manual = "manual",
            continueLabel = "skip",
            onboardingTitle = "get connected",
            onboardingSubtitle = "import a config file or open the profile editor for manual setup",
            allTraffic = "all traffic",
            onlySelected = "only selected",
            exceptSelected = "all except selected",
            apps = "apps",
            relay = "relay",
            userId = "user id",
            dns = "dns",
            autoFailover = "auto failover",
            current = "active",
            routingSummary = "routing mode",
            saveProfile = "save profile",
            status = "status",
            detail = "detail",
            engine = "engine",
            ready = "ready",
            missing = "missing",
            servers = "servers",
            priority = "priority",
            notSet = "not set",
            relayNotConfigured = "Relay not configured",
            profileField = "profile",
            port = "port",
            tun = "tun",
            mtu = "mtu",
            keepSessionAliveHint = "keep the session alive when the active path changes",
            importedFrom = "Imported from",
            serversHint = "vpncore receives the full servers[] array and picks the target on its own.",
            addServer = "add server",
            remove = "remove",
            server = "server",
            serverId = "server id",
            serverKey = "server key",
            loading = "loading...",
            saving = "saving...",
            preparingWorkspace = "Preparing workspace...",
            showSystemApps = "show system apps",
            showSystemAppsHint = "include platform packages in the list",
            search = "search",
            noAppsFound = "No apps found",
            noAppsFoundHint = "Change the search query or include system apps to see more packages.",
            noPerAppSelectionHint = "No per-app selection is needed in this mode.",
            onboardingImportHint = "client.yaml / client.json",
            onboardingManualHint = "relay, user id, servers[]",
            onboardingContinueHint = "open the dashboard without importing now",
            readSavedRoutingState = "Reading saved routing state...",
            readSplitRoutingState = "Reading split routing mode and installed apps from storage.",
            failedReadSelectedFile = "Failed to read the selected file.",
            unableToOpenSelectedConfigFile = "Unable to open the selected config file.",
            failedImportSelectedFile = "Failed to import the selected file.",
            failedImportConfig = "Failed to import config.",
            atLeastOneServerRequired = "At least one server is required.",
            profileSaved = "Profile saved",
            failedSaveProfile = "Failed to save profile.",
            failedSaveRoutingSettings = "Failed to save routing settings.",
            config = "config",
        )
    }
}

fun MaydayStrings.serverCountLabel(count: Int): String {
    return when (locale) {
        AppLanguage.RU -> "$count ${russianServers(count)}"
        AppLanguage.EN -> "$count ${if (count == 1) "server" else "servers"}"
    }
}

fun MaydayStrings.serverTitle(index: Int): String {
    return "$server $index"
}

fun MaydayStrings.importedServersMessage(count: Int): String {
    return when (locale) {
        AppLanguage.RU -> "Импортировано $count ${russianServers(count)}"
        AppLanguage.EN -> "Imported ${serverCountLabel(count)}"
    }
}

fun MaydayStrings.importedConfigMessage(sourceName: String): String {
    return when (locale) {
        AppLanguage.RU -> "Импортирован ${sourceName.ifBlank { config }}"
        AppLanguage.EN -> "Imported ${sourceName.ifBlank { config }}"
    }
}

private fun russianServers(count: Int): String {
    val mod10 = count % 10
    val mod100 = count % 100
    return when (mod10) {
        1 if mod100 != 11 -> "сервер"
        in 2..4 if mod100 !in 12..14 -> "сервера"
        else -> "серверов"
    }
}
